config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'doctors/new'
  get 'doctors/create'
  get 'doctors/show'
  get 'doctors/index'

  # root "pateints/sign_in"
  # root :to => "devise/sessions#new"
  # devise_for :admins, path: 'admins'
  # devise_scope :admin do
  # authenticated :admin do
  #   root 'home#index', as: :authenticated_root
  # end
  # end
  root :to => redirect("/pateints/sign_in")


  get 'appointments/create'
  get 'appointments/new'
  get 'appointments/edit'
  get 'appointments/update'
  get 'appointments/index'
  devise_for :pateints, controllers: {
          sessions: 'pateints/sessions',
          registrations: 'pateints/registrations'

        }

  resources :appointments

end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :pateint

  def self.ransackable_attributes(auth_object = nil)
    ["address", "age", "created_at", "disease", "doctor_id", "id", "name", "pateint_id", "updated_at"]
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

  def new
    @appointment = Appointment.new
  end

  def create
    @appointment = current_pateint.appointments.new(appointment_params)
    UserMailer.welcome_email(current_pateint).deliver_now
    if @appointment.save!
      redirect_to @appointment
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @appointment = Appointment.find(params[:id])
  end

  def index
    @appointment = Appointment.all
  end

  private

  def appointment_params
    params.require(:appointment).permit(:name, :age, :address, :disease, :doctor_id)
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/index.html.erb
<h1>All Appointments</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Age</th>
      <th>Address</th>
      <th>Disease</th>
      <th>Doctor_id</th>
      <th>Pateint_id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointment.each do |appointment| %>
      <tr>
        <td><%= appointment.id %></td>
        <td><%= appointment.name %></td>
        <td><%= appointment.age %></td>
        <td><%= appointment.address %></td>
        <td><%= appointment.disease %></td>
        <td><%= appointment.doctor_id %></td>
        <td><%= appointment.pateint_id %></td>
        <td><%= link_to "view", appointment %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


  <%= button_to "Sign out", destroy_pateint_session_path, method: :delete %>
  <%= button_to "Book appointment", appointments_new_path, method: :get %>

app/views/appointments/new.html.erb
<h1>Book appointment</h1>

<%= form_with model: @appointment do |form| %>

  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age %><br>
    <%= form.text_field :age %>
  </div>

  <div>
    <%= form.label :address %><br>
    <%= form.text_area :address %>
  </div>

  <div>
    <%= form.label :disease %><br>
    <%= form.text_area :disease %>
  </div>

  <div>
    <%= form.label :doctor %><br>
    <%= form.collection_select :doctor_id, Doctor.order(:name), :id, :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/appointments/show.html.erb
<strong>name: </strong> <%= @appointment.name %><br />
<strong>age: </strong> <%= @appointment.age %><br />
<strong>address: </strong> <%= @appointment.address %><br />
<strong>disease: </strong> <%= @appointment.disease %><br />
<strong>doctor: </strong> <%= @appointment.doctor_id %>